#!/bin/bash

eval `curl -sfq http://169.254.169.254/latest/user-data`
CEPH_FSID=`/usr/local/bin/consul-get-or-set /$NUBIS_STACK/$NUBIS_ENVIRONMENT/storage/fsid uuidgen`
REGION=`curl -sfq http://169.254.169.254/latest/dynamic/instance-identity/document | jq '.region' -r`
INSTANCE_ID=`curl -sfq curl http://169.254.169.254/latest/meta-data/instance-id`

set -x

#XXX: Only one member of the cluster should ever run this
#XXX: so if we are not the current leader, forget about it and bail out
consul-do ceph-fsid-$CEPH_FSID $INSTANCE_ID verbose || exit

function ceph_unmount {
  if [ -d /tmp/ceph ]; then
    umount -l /tmp/ceph
    rmdir /tmp/ceph
  fi
}

trap ceph_unmount INT EXIT

mkdir -p /tmp/ceph

mount -t ceph -oro ceph-fsid-$CEPH_FSID.ceph-mon.service.consul:/ /tmp/ceph || exit

aws --region $REGION s3 sync /tmp/ceph/ s3://$NUBIS_STORAGE_BUCKET/ --delete
