#!/bin/bash

eval `curl -fq http://169.254.169.254/latest/user-data`
CEPH_FSID=`/usr/local/bin/consul-get-or-set /$NUBIS_STACK/$NUBIS_ENVIRONMENT/storage/fsid uuidgen`
REGION=`curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq '.region' -r`

set -x

mkdir -p /tmp/ceph

function ceph_unmount {
  umount -l /tmp/ceph
  rmdir /tmp/ceph
}

trap ceph_unmount INT EXIT

mount -t ceph -oro ceph-fsid-$CEPH_FSID.ceph-mon.service.consul:/ /tmp/ceph

aws --region $REGION s3 sync /tmp/ceph/ s3://$NUBIS_STORAGE_BUCKET/ --delete
